---
on:
  pull_request:

jobs:
  markdown-lint:
    uses: Stromweld/github-workflows/.github/workflows/markdown-lint.yml@main

  yaml-lint:
    uses: Stromweld/github-workflows/.github/workflows/yaml-lint.yml@main

  terraform-lint:
    uses: Stromweld/github-workflows/.github/workflows/terraform-lint.yml@main
    secrets: inherit

  terraform-plan:
    uses: Stromweld/github-workflows/.github/workflows/terraform-plan.yml@main
    secrets: inherit

  check:
    if: always()
    needs:
      - markdown-lint
      - yaml-lint
      - terraform-lint
      - terraform-plan
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-failures:
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
